- hosts: all
  sudo: true
  user: vagrant
  tasks:
    - name: install basic package
      apt: name={{item}} update_cache=yes cache_valid_time=3600
      with_items:
        - git
        - vim
        - ntp
        - emacs
        - build-essential
        - libssl-dev