- hosts: localhost
  vars_files:
  - ../vars/secret.yml
  sudo: yes
  user: vagrant
  tasks:
    - name: create mysql user
      mysql_user: name={{ database.user }} host=localhost password={{ database.password }} priv={{ database.database }}.*:ALL,GRANT
    - name: set env vars for rails
      shell: echo "export DB_USERNAME={{ database.user }}\nexport DB_PASSWORD={{ database.password }}\nexport DB_DATABASE={{ database.database }}" >> /etc/profile.d/database.sh
    - name: set env vars for active admin
      shell: echo "export ADMIN_EMAIL={{ admin.email }}\nexport ADMIN_PASSWORD={{ admin.password }}" >> /etc/profile.d/database.sh