# twitter 利用のセットアップ
# このファイルをコピーしてsecrets.ymlに名前を変更することによって使用できます
# 各種keyはtiwtterで登録して取得してください(https://apps.twitter.com/)

default: &default
  twitter_consumer_key: ""
  twitter_consumer_secret: ""
  twitter_access_token: ""
  twitter_access_token_secret: ""

development:
  <<: *default

test:
  <<: *default

production:
  twitter_consumer_key:  ""
  twitter_consumer_secret:  ""
  twitter_access_token:  ""
  twitter_access_token_secret:  ""